### ISSUE TITLE
Not a 1-1 mapping between currencies and symbols

### ISSUE THREAD

**Issue by bengourley** [bengourley/currency-symbol-map#23]
While I was reviewing the tests for #22, I noticed an issue. @bestan this relates to the work you did to implement the reverse mapping from symbols back to currencies (#13).

I don't if it was the situation at the time (I haven't checked) but it certainly is the case now – there's a 1-many mapping between symbols and currency codes. This means working out the code from the symbol is non-deterministic. Because of the way it's implemented, the actual implementation chooses the last code to have been added to the map.

So for example before the changes in #22:

```js
getCurrencyFromSymbol('$') === 'USD'
```

and after:

```js
getCurrencyFromSymbol('$') === 'XCD'
```

Any thoughts @bestan?

**Comment by bestan** [comment]
I can see two options:

1) We restrict symbols to being unique. For example, AUD is represented as `A$` or `AU$` ([source](http://www.investopedia.com/terms/forex/a/aud-australian-dollar.asp)). I'm sure other `$` currency code would have similar representations.

**Significant drawback**: Australians are likely to use `$` locally instead of the prefixed symbol. Applications built for local markets wouldn't look as expected.

2) We add country to the map, refactoring the call to `getCurrencyForSymbolAndCountry('$', 'AU')` or something like that. Perhaps this is the best approach, but requires significantly more effort.

**Comment by bengourley** [comment]
I'm pretty easy on this. I don't use the reverse look up at all. Did you have a use case for it when you implemented it? If not I'd be tempted to remove the function completely and bump a major version.

**Comment by bestan** [comment]
I was building a prototype, which I'm not using anymore, so I'm quite easy on this too. The use case was parsing strings like "$20" and converting to other currency.

**Comment by bengourley** [comment]
I'd be happiest to deprecate it entirely then, if that's ok with you?

**Comment by bestan** [comment]
Sure
