### ISSUE TITLE
ES6 Documentation

### ISSUE THREAD

**Issue by crashspringfield** [bengourley/currency-symbol-map#27]
I'm currently using this in a project written in ES6 / ECMAScript2015. If you'd like, I can add an ES6 usage example to the docs.

**Comment by bengourley** [comment]
Hi Matthew, glad the project is of use to you!

I'm interested to see how your es6 usage is different… after all the code
in the readme is valid es6!

I guess you're going to mention `import`? Feel free to open up a PR if you
think it will be useful!

**Comment by crashspringfield** [comment]
I've been wanting to start contributing to open source projects and figured I'd start with the little "I could do that" instances.

I tried to push the edited README but got a 'permission denied' and 403.

**Comment by bengourley** [comment]
You'll need to "fork" this repo then make a "pull request" – you can't just push code to other people's repositories (which is why you get "permission denied"), you need to push it to your own and request that an owner of the original incorporates your change.

This guide should be useful https://help.github.com/articles/fork-a-repo/#propose-changes-to-someone-elses-project

Hope this helps!

**Comment by bengourley** [comment]
Closed by #28.
